Structure README.md
isaacs/github pull request #1706
Opened 2019-12-13 05:01 UTC by sypets

- reorder the part about creating issues and add a numbered list for better readability
- add subheaders in README.md
- link to CONTRIBUTING.md
- Add information about how to upvote issues

2020-04-17 17:16 UTC, TPS commented
@sypets Do you mind resolving the conflict I introduced by updating the GitHub contact link?

2020-07-02 17:41 UTC, sypets commented
Sorry about the late reaction. Is fixed now.

2020-09-19 06:06 UTC, safinsingh requested changes

2020-09-19 06:06 UTC, safinsingh commented on README.md
> +## If you have an issue or feature request for GitHub.
Extra period in heading

2020-09-19 06:06 UTC, safinsingh commented on README.md
> +1. Search for existing [issues](https://github.com/isaacs/github/issues) here first
You can drop the `first` at the end, it's already the first item in an ordered list.

2020-09-19 06:06 UTC, safinsingh commented on README.md
> +2. If you did not find any existing issue for your topic, post a new issue.
Extra period in single-sentence list item

2020-09-24 19:38 UTC, sypets commented
I cleaned up my workspace and deleted the fork because I did not realize I still had a PR open. I did not see any other possibility than to create a new PR: #1852 

I resolved all comments and added the changes. Sorry.

2020-09-24 19:38 UTC, closed without merging